# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Bridge to Ocean Acoustics and Technology
author: BOAT developers
logo: ""
copyright: '2025'
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off
  timeout: -1

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: boat_tutorials.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/OSOceanAcoustics/BOAT_Acoustics  # Online location of your book
  path_to_book: boat_tutorials  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_edit_page_button: true
  use_repository_button: true

sphinx:
  recursive_update: true  # needed to default to light mode
  extra_extensions: [
    # 'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.githubpages',
    # 'sphinx_exercise'
  ]
  config:
    bibtex_reference_style: author_year
  # Default to light mode
  # See: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/light-dark.html#configure-default-theme-mode
  html_context:
    default_mode: light